### DISCUSSION TITLE
Example validation

### DISCUSSION THREAD

**Discussion by andreicodreanuwp** [skryukov/skooma#31] [General]
Hello,

First of all, congratulations! I've been following this gem for a while and I was very tempted to use it in a numerous occasions. Today I had the opportunity to create an external API and decided to give it a try since Apipie does not have a support for separate set of controllers. It went really fast and was very pleased with the result. The only thing that felt missing from testing the endpoints was having a different expect for each scenarios of the same error code. I noticed in the future plans you mentioned this is on the list as well. Do we have any timeline for these plans?

Thank you!

**Comment by skryukov** [comment]
Hey @codrutzu, thanks for the kind words!

> The only thing that felt missing from testing the endpoints was having a different expect for each scenarios of the same error code.

Could you elaborate on what you're trying to achieve? Are you asking about the ability to define and test different response bodies for the same HTTP status code, for schemes like this:

```yaml
paths:
  /foo:
    post:
      responses:
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationError'
                  - $ref: '#/components/schemas/AnotherError'
```

**Reply by andreicodreanuwp** [reply]
Yes! Although I structured the response something like this 
```
        "422":
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string
              examples:
                param_missing:
                  summary: Missing required parameter id or secret
                  value:
                    message: 'Parameter missing: secret'
                    code: unprocessable_entity
                invalid_credentials:
                  summary: Invalid client id or secret
                  value:
                    message: Invalid credentials
                    code: unprocessable_entity
```

In RSpec: 
```
  context 'when client secret is invalid' do
    let(:params) { { id: application.id, secret: 'invalid-secret' } }

    it 'returns an error message' do
      request

      expect(response).to conform_schema(422)
    end
  end

  context 'when client id is invalid' do
    let(:params) { { id: 'invalid-id', secret: application.secret } }

    it 'returns an error message' do
      request

      expect(response).to conform_schema(422)
    end
  end
```

The part missing was to test these two different scenarios invalid credentials and parameter missing. The way I would expect to write the spec would then be: 
`expect(response).to conform_schema(422, :param_missing)`
`expect(response).to conform_schema(422, :invalid_credentials)`

I didn't think of a scenario where a HTTP status code could have multiple response formats but I guess that would be a valid case to handle as well. 🤔 

And one more thing if you don't mind, I can see using a single file to become very tedious to maintain and I could not find anything in the documentation that address that. Is there any way to split it based on controllers perhaps?
