### ISSUE TITLE
Multiple types yields JSONSchema-compatible TypeError

### ISSUE THREAD

**Issue by earoberson** [skryukov/skooma#44]
Great project, thank you for maintaining. 

I have a response body where a field is nullable, but the non-null type is formatted. After reviewing valid OpenAPI 3.1 spec, it seems the following is permitted and handled in several code generators:

```
properties:
  a_nullable_string:
    - type: string
      format: date-time
    - type: 'null'
```

However, this yields the following when including `Skooma::Rspec` in rails_helper.rb.

```
TypeError:
  [{"type"=>"string", "format"=>"date-time"}, {"type"=>"null"}] is not JSONSchema-compatible
```

Is it expected behavior to raise an exception on loading Skooma in rails_helper.rb if the JSON Schema is invalid?

If allowing the above seems to be ok, can I open a PR against addressing this?
